<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1KGX0vW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1KGX0vW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1KGX0vW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1KGX0vW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1KGX0vW\App_KernelDevDebugContainer([
    'container.build_hash' => '1KGX0vW',
    'container.build_id' => '0a4e927d',
    'container.build_time' => 1613080218,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1KGX0vW');
