<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9vEG3HG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9vEG3HG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9vEG3HG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9vEG3HG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9vEG3HG\App_KernelDevDebugContainer([
    'container.build_hash' => '9vEG3HG',
    'container.build_id' => 'f0baa6be',
    'container.build_time' => 1611267470,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9vEG3HG');
