<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVaBDjjB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVaBDjjB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVaBDjjB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVaBDjjB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVaBDjjB\App_KernelDevDebugContainer([
    'container.build_hash' => 'VaBDjjB',
    'container.build_id' => '3224203a',
    'container.build_time' => 1590410487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVaBDjjB');
