version: "3.5"

services:
  acm-nginx:
    image: nginx:1-alpine
    container_name: acm-nginx
    working_dir: /app
    expose:
      - 80
    volumes:
      - ../app:/app:z
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:z
    networks:
      - airclubmanager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`blog.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web"
  acm-php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: php-symfony:v1
    container_name: acm-php
    working_dir: /app
    volumes:
      - ../app:/app:z
    networks:
      - airclubmanager

  acm-mariadb:
    image: mariadb:10.5
    container_name: acm-mariadb
    expose:
      - 3306
    volumes:
      - ./mariadb:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=acm
      - MYSQL_USER=acm
      - MYSQL_PASSWORD=acm
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mariadb.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mariadb.entrypoints=mariadb"
      - "traefik.tcp.routers.mariadb.service=mariadb-svc"
      - "traefik.tcp.services.mariadb-svc.loadbalancer.server.port=3306"
    networks:
      - airclubmanager

  acm-traefik:
    image: traefik:v2.4
    container_name: acm-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    networks:
      - airclubmanager

networks:
  airclubmanager:
